# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g., lanes or resequencing of the same biological
# sample).
units: units.tsv

genome: "data/genome/potato_dm_v404_all_pm_un.fasta"

# sequencing adapter
adapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTGTTCCTGAGTGTAGATCTCGGTGGTCGCCGTATCATT

params:
    cutadapt-pe: "-q 10 -m 40 -j 8"
    cutadapt-se: "-q 10 -m 40 -j 8"
    align:
        bwa_threads: 12
        sort_threads: 4

diploid_bams:
    - data/dedup/2x_vt_sup_h47-SRR3994197-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3994196-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3994310-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3994457-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3994569-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3994708-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3995206-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3995207-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3995208-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3995209-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3995210-dedup-sorted.aln.bam
    - data/dedup/2x_vt_sup_h47-SRR3995211-dedup-sorted.aln.bam
    - data/dedup/2x_IVP101-SRR6123183-dedup-sorted.aln.bam

tetraploid_bams:
    - data/dedup/4x_superior-SRR2069940-dedup-sorted.aln.bam
    - data/dedup/4x_superior-SRR2069941-dedup-sorted.aln.bam
    - data/dedup/4x_superior-SRR2069942-dedup-sorted.aln.bam
    - data/dedup/4x_superior-SRR2070067-dedup-sorted.aln.bam

bam_indexes:
    - data/dedup/2x_vt_sup_h47-SRR3994197-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3994196-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3994310-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3994457-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3994569-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3994708-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3995206-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3995207-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3995208-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3995209-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3995210-dedup-sorted.aln.bam.bai
    - data/dedup/2x_vt_sup_h47-SRR3995211-dedup-sorted.aln.bam.bai
    - data/dedup/2x_IVP101-SRR6123183-dedup-sorted.aln.bam.bai
    - data/dedup/4x_superior-SRR2069940-dedup-sorted.aln.bam.bai
    - data/dedup/4x_superior-SRR2069941-dedup-sorted.aln.bam.bai
    - data/dedup/4x_superior-SRR2069942-dedup-sorted.aln.bam.bai
    - data/dedup/4x_superior-SRR2070067-dedup-sorted.aln.bam.bai

diploid_gvcfs:
    - data/calls/gatk/2x_vt_sup_h47-SRR3994197.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3994196.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3994310.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3994457.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3994569.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3994708.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3995206.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3995207.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3995208.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3995209.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3995210.g.vcf
    - data/calls/gatk/2x_vt_sup_h47-SRR3995211.g.vcf
    - data/calls/gatk/2x_IVP101-SRR6123183.g.vcf

tetraploid_gvcfs:
    - data/calls/gatk/4x_superior-SRR2069940.g.vcf
    - data/calls/gatk/4x_superior-SRR2069941.g.vcf
    - data/calls/gatk/4x_superior-SRR2069942.g.vcf
    - data/calls/gatk/4x_superior-SRR2070067.g.vcf
