channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.3.1
  - bedtools=2.27.1
  - biopython
  - bwa=0.7.12
  - cutadapt=1.15
  - freebayes=1.1.0
  - graphviz=2.38.0
  - gatk4=4.0.1.2
  - picard=2.14
  - python=3.5.1
  - samtools=1.3.1
  - sra-tools=2.8.2
  - snakemake=3.11.0
  - pyyaml=3.11
  - pandas=0.20.3
  - parallel
  - vcflib=1.0.0_rc1
